# Generated by Django 5.1 on 2024-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_productsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computers', 'Computers'), ('Food', 'Food'), ('cars', 'Kids'), ('Home', 'Home')], max_length=40),
        ),
    ]
